[package]
name = "sui-open-rpc"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sui-open-rpc-macros = { path = "macros" }
sui-types = { path = "../../sui_types" }
schemars = "0.8.8"
serde = "1.0.136"